name: CD - Deploy to EC2 with Docker

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Pull Docker images from DockerHub
      - name: Pull Docker images for frontend and backend
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/cs360_test_frontend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/cs360_test_backend:latest

      # Step 4: Deploy to EC2
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}  # ใช้ GitHub secret สำหรับ private key
          script: |
            # Pull และรัน Docker images บน EC2 instance
            docker stop frontend || true
            docker rm frontend || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/cs360_test_frontend:latest
            docker run -d --name frontend -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/cs360_test_frontend:latest

            docker stop backend || true
            docker rm backend || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/cs360_test_backend:latest
            docker run -d --name backend -p 1337:1337 ${{ secrets.DOCKER_USERNAME }}/cs360_test_backend:latest

            # ตรวจสอบสถานะของ containers
            docker ps
