name: Node.js CI

on:
  push:
    branches: [ test-feature07, test-feature08, test-feature06]

  pull_request:
    branches: [ develop, main ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu:latest', 'debian:latest', 'redhat/ubi8']
        node-version: [16.x]

    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install yarn
      run: npm install -g yarn
    
    - name: Install api dependencies
      working-directory: ./api
      run: |
        yarn add @babel/runtime
        yarn 
        yarn seed
        echo "JWT_SECRET=test-jwt-secret" >> .env
        echo "ADMIN_JWT_SECRET=test-admin-jwt-secret" >> .env

    - name: Install client dependencies
      working-directory: ./client
      run: |
        yarn
    
    - name: Run api unit tests
      working-directory: ./api
      run: |
        yarn test:unit

    - name: Run client unit tests
      working-directory: ./client
      run: |
        yarn test:unit
    
    - name: Run client integration tests
      working-directory: ./client
      run: |
        yarn test:integration
