name: Node.js CI

on:
  push:
    branches: [ test-feature06 ]
  pull_request:
    branches: [ develop-feature06, develop, main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, debian, redhat]
        node-version: [16.x, 18.x]
    
    runs-on: self-hosted-${{ matrix.os }}
    
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json'
    
    - name: Install build essentials
      run: |
        sudo yum groupinstall "Development Tools" -y
        sudo yum install gcc gcc-c++ make -y
        
    - name: Install dependencies
      run: |
        npm install
        npm install -g jest
    
    - name: Test
      run: npm test
